### ISSUE TITLE
Transition to using Garage API v2

### ISSUE THREAD

**Issue by ibnzterrell** [UCFParking/UCFParkingAgent#13]
Transition from using Garage API v1 to API v2

**Comment by ibnzterrell** [comment]
Since clarification was requested, we would be transitioning from using API v1:
"/prediction/:weekday/:hour/:minute"
to API v2:
"/api/v2/garage/:garage/prediction/:weekday/:hour/:minute"

**Comment by nayoshi** [comment]
prediction-ucf-garage.js supports v1 and v2 of Prediction API
